### PR TITLE
Expose curl_geinfo

### PR DESCRIPTION
**Pull request by allflame**
Added a method to fetch curl_getinfo from the curl resource.

### CODE REVIEW

**Comment by mekras** [comment]
What the purpose of this method?

**Comment by allflame** [comment]
@mekras I'm not even sure how to describe this more direct.
There is no way to inject any logging for connection times, ns lookups etc, which is provided by curl_getinfo. The solution is either to expose the resource itself (which is potentially dangerous) or to expose it's state, e.g. through curl_getinfo

**Comment by mekras** [comment]
It doesn't make sense, because curl-client is just an implementation of [HttpClient interface](https://github.com/php-http/httplug/blob/master/src/HttpClient.php), which doesn't have this method. So it will be unusable.

**Comment by Nyholm** [comment]
Im 👎 
I just removed this function from Buzz. See https://github.com/kriswallsmith/Buzz/pull/291

I would rather add more data to the exception thrown.

**Comment by allflame** [comment]
The case was not only to fetch data during errors, but for successful requests as well.
The other option would be to decorate the response that is generated by the Client, but guess what - all functions are made private and there is "new ResponseBuilder" instatination right there.

**Pull request closed without merging**
