### PR TITLE
Make sure discovery can find the curl client

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by hpatoio** [comment]
Why is this commit on `puli` branch and not on `master` ?

**Comment by sagikazarmark** [comment]
Because the PR is not yet merged.

**Comment by hpatoio** [comment]
Let's reword my question. Why is `puli` branch not merged in `master` ? It seems to me that the commit is correct but maybe I miss something.

I set `"php-http/curl-client": "puli-dev@dev"` in my `composer.json` so I'm ok now. 

Thanks

**Comment by Nyholm** [comment]
Thank you for testing and reviewing this PR.

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
