### PR TITLE
We do also provide async client

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by dbu** [comment]
makes sense. looks like the test failures have nothing to do with your change. just merge it if you want. we should fix the failures in a separate PR.

**Comment by Nyholm** [comment]
Those failures has nothing to do with the client. They are Puli related. I know @sagikazarmark made a fix for that on some repo but I can't find it.

**Comment by sagikazarmark** [comment]
You mean this one?

https://github.com/puli/issues/issues/190

You need a custom bootstrap file for the tests to make it work.

**Comment by mekras** [comment]
I'll do this.

**Pull request merged**
